import { useEffect, useRef, useState, type ChangeEvent } from "react";
import type { InboxItem } from "@radar/shared";
import { extractPdfText, fileToBase64 } from "../lib/pdf";
import PageHeader from "../components/layout/PageHeader";
import StatusMessage from "../components/ui/StatusMessage";

const STATUS_LABEL: Record<string, string> = { received: "접수됨", stored: "보존됨", extracted: "텍스트 추출됨", analyzed: "분석됨", indexed: "색인됨", failed: "처리 실패" };

export default function InboxView() {
  const [items, setItems] = useState<InboxItem[]>([]); const [msg, setMsg] = useState(""); const [busy, setBusy] = useState(false); const [title, setTitle] = useState(""); const [text, setText] = useState(""); const [url, setUrl] = useState(""); const fileRef = useRef<HTMLInputElement | null>(null);
  async function load() { try { const response = await fetch("/api/inbox"); const data = await response.json() as { items?: InboxItem[] }; setItems(data.items ?? []); } catch { setItems([]); } }
  useEffect(() => { void load(); }, []);
  async function post(path: string, body: unknown) { setBusy(true); setMsg(""); try { const response = await fetch(`/api/inbox${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json() as Record<string, unknown>; if (!response.ok) { setMsg(`처리하지 못했습니다: ${String(data.error ?? response.status)}`); return null; } return data; } catch (error) { setMsg(`연결하지 못했습니다: ${(error as Error).message}`); return null; } finally { setBusy(false); } }
  async function addNote() { if (!text.trim()) return; const data = await post("/text", { text, title: title || undefined }); if (data) { setMsg(data.duplicateOf ? "이미 저장된 자료와 연결했습니다." : `메모를 보존했습니다: ${String(data.title)}`); setTitle(""); setText(""); void load(); } }
  async function addUrl() { if (!url.trim()) return; const data = await post("/url", { url }); if (data) { setMsg(data.error ? `원문을 가져오지 못했지만 재시도할 수 있게 남겼습니다: ${String(data.error)}` : data.duplicateOf ? "이미 저장된 자료와 연결했습니다." : `원문을 보존했습니다: ${String(data.title)}`); setUrl(""); void load(); } }
  async function onFile(event: ChangeEvent<HTMLInputElement>) { const files = event.target.files; if (!files) return; for (const file of Array.from(files)) { try { if (/\.(md|markdown|txt)$/i.test(file.name)) { const data = await post("/file", { filename: file.name, text: await file.text() }); if (data) setMsg(data.duplicateOf ? "이미 저장된 자료와 연결했습니다." : `${file.name}을 보존했습니다.`); } else if (/\.pdf$/i.test(file.name)) { setMsg(`${file.name}에서 텍스트를 추출하는 중입니다.`); const extracted = await extractPdfText(file); const hasText = extracted.text.replace(/\[page \d+\]|\s/g, "").length >= 20; const originalBase64 = file.size <= 10_000_000 ? await fileToBase64(file) : undefined; const data = await post("/file", { filename: file.name, text: hasText ? extracted.text : undefined, originalBase64, contentType: "application/pdf" }); if (data) setMsg(data.duplicateOf ? "이미 저장된 자료와 연결했습니다." : hasText ? `${file.name}을 보존했습니다. (${extracted.pageCount}쪽)` : `${file.name}은 스캔 PDF입니다. 원본만 보존했으며 핵심 문장을 메모로 추가해 주세요.`); } else setMsg(`${file.name}: 지원하지 않는 파일 형식입니다.`); } catch (error) { setMsg(`${file.name}: 처리하지 못했습니다. ${(error as Error).message}`); } } event.target.value = ""; void load(); }
  async function retry(sourceId: string) { const data = await post(`/retry/${sourceId}`, {}); setMsg(data?.ok ? "재시도를 완료했습니다." : "재시도하지 못했습니다. 상태를 확인해 주세요."); void load(); }

  return <div className="view-stack"><PageHeader title="받은편지함" description="메모, 링크, 파일을 먼저 원본 그대로 보존합니다. 분석은 그 다음 단계입니다." />
    <div className="inbox-layout"><section className="inbox-capture" aria-label="자료 입력"><div className="inbox-tabs"><span className="inbox-tabs__active">메모·텍스트</span><span>URL</span><span>파일</span></div><label>제목<span className="table-note">선택</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="자료를 구분할 제목" /></label><label>내용<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="읽은 문장이나 메모를 붙여 넣으세요" /></label><button className="ui-button" disabled={busy || !text.trim()} onClick={() => void addNote()}>메모 보존하기</button><div className="inbox-divider"><span>또는 원문 링크</span></div><label>URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://" /></label><button className="ui-button-secondary" disabled={busy || !url.trim()} onClick={() => void addUrl()}>원문 가져와 보존하기</button><div className="inbox-divider"><span>또는 파일</span></div><input ref={fileRef} type="file" accept=".md,.markdown,.txt,.pdf" multiple onChange={(event) => void onFile(event)} /><p className="table-note">Markdown, TXT, PDF · PDF 원본은 R2에 함께 보존됩니다.</p></section><section className="inbox-list"><div className="inbox-list__heading"><div><p className="reading-section__label">처리 목록</p><h2>최근 들어온 자료</h2></div><span className="table-note">{items.length}개</span></div>{msg && <p className="reservoir-message" role="status">{msg}</p>}{items.length === 0 ? <StatusMessage kind="empty" title="아직 들어온 자료가 없습니다" description="왼쪽에서 메모, 링크, 파일을 추가해 보세요." /> : <div className="inbox-items">{items.map((item) => <article className="inbox-item" key={item.sourceId}><div><span className={`status-dot status-dot--${item.status}`} /> <strong>{item.title}</strong><p>{STATUS_LABEL[item.status] ?? item.status} · {item.kind} · {item.origin ?? "출처 없음"} · {item.createdAt?.slice(0, 10)}</p>{item.error && <span className="inbox-item__error">{item.error.slice(0, 120)}</span>}</div>{item.status === "failed" && <button className="ui-button-secondary" disabled={busy} onClick={() => void retry(item.sourceId)}>다시 시도</button>}</article>)}</div>}</section></div>
  </div>;
}
