import { useEffect, useState } from "react";
import { PRESETS, type PresetName, type RadarParams } from "@radar/shared";
import PageHeader from "../components/layout/PageHeader";
import StatusMessage from "../components/ui/StatusMessage";

const PARAM_FIELDS: { key: keyof RadarParams; label: string; left: string; right: string }[] = [{ key: "familiarity", label: "익숙함", left: "새로운 영역", right: "기존 관심사" }, { key: "researchDepth", label: "연구 깊이", left: "가볍게 탐색", right: "깊이 파고들기" }, { key: "divergence", label: "발산 정도", left: "응집된 연결", right: "뜻밖의 연결" }, { key: "counterStrength", label: "반대 관점", left: "부드러운 반론", right: "강한 반대 미학" }, { key: "technicalPhotographic", label: "기술 ↔ 사진", left: "시스템·기술", right: "이미지·물질" }];
const PRESET_LABELS: Record<PresetName, string> = { BALANCED: "균형", DEEP_RESEARCH: "깊은 연구", ARTWORK_EXPLORATION: "작업 탐색", COUNTER_HEAVY: "반대 관점 강화", TECHNICAL: "기술 중심" };

export default function SettingsView() {
  const [params, setParams] = useState<RadarParams | null>(null); const [msg, setMsg] = useState(""); const [exportMsg, setExportMsg] = useState(""); const [homepageMsg, setHomepageMsg] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/settings/params").then((response) => response.json() as Promise<RadarParams>).then(setParams).catch(() => setParams(null)); }, []);
  async function save(next: RadarParams) { setParams(next); setBusy(true); try { const response = await fetch("/api/settings/params", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(next) }); setMsg(response.ok ? "연구 성향을 저장했습니다." : `저장하지 못했습니다: ${response.status}`); } catch (error) { setMsg(`저장하지 못했습니다: ${(error as Error).message}`); } finally { setBusy(false); } }
  async function action(path: string, setter: (message: string) => void, success: (data: Record<string, unknown>) => string) { setBusy(true); try { const response = await fetch(path, { method: "POST" }); const data = await response.json() as Record<string, unknown>; setter(response.ok ? success(data) : `작업을 완료하지 못했습니다: ${response.status}`); } catch (error) { setter(`연결하지 못했습니다: ${(error as Error).message}`); } finally { setBusy(false); } }
  return <div className="view-stack"><PageHeader title="설정" description="발견과 착즙이 자료를 읽는 방식에 맞게 작동하도록 조정합니다." />
    <section className="settings-section"><h2>연구 성향</h2><p>이 값은 발견 후보의 방향과 착즙의 균형에 반영됩니다.</p>{params ? <>{PARAM_FIELDS.map((field) => <label className="settings-range" key={field.key}><span className="settings-range__heading"><span>{field.label}</span><span>{params[field.key].toFixed(2)}</span></span><input type="range" min={0} max={1} step={0.05} value={params[field.key]} disabled={busy} onChange={(event) => setParams({ ...params, [field.key]: Number(event.target.value) })} onMouseUp={() => void save(params)} onTouchEnd={() => void save(params)} /><span className="settings-range__ends"><span>{field.left}</span><span>{field.right}</span></span></label>)}{msg && <p className="reservoir-message" role="status">{msg}</p>}</> : <StatusMessage kind="loading" title="연구 성향을 불러오는 중입니다" />}</section>
    <section className="settings-section"><h2>빠른 프리셋</h2><p>자주 쓰는 읽기 모드를 바로 적용합니다.</p><div className="settings-actions">{(Object.keys(PRESETS) as PresetName[]).map((preset) => <button key={preset} className="filter-button" disabled={busy} onClick={() => void save(PRESETS[preset])}>{PRESET_LABELS[preset]}</button>)}</div></section>
    <section className="settings-section"><h2>홈페이지 연결</h2><p>taejunyun.com의 프로젝트 정보를 발견 맥락에 반영합니다. 원본 데이터는 별도로 보존됩니다.</p><button className="ui-button-secondary" disabled={busy} onClick={() => void action("/api/settings/import-homepage", setHomepageMsg, (data) => `프로젝트 ${data.imported ?? 0}개를 가져왔습니다. 중복 ${data.duplicates ?? 0}개.`)}>홈페이지 프로젝트 다시 가져오기</button>{homepageMsg && <p className="reservoir-message" role="status">{homepageMsg}</p>}</section>
    <section className="settings-section"><h2>데이터 내보내기</h2><p>원본과 분석 결과를 필요한 형식으로 내려받습니다.</p><div className="settings-actions"><a className="ui-button-secondary" href="/api/export/json" download>전체 JSON</a><a className="ui-button-secondary" href="/api/export/markdown" download>마크다운</a><a className="ui-button-secondary" href="/api/export/csv" download>자료 CSV</a><button className="ui-button-secondary" disabled={busy} onClick={() => void action("/api/export/originals-to-r2", setExportMsg, (data) => `원본 ${data.copied ?? 0}/${data.total ?? 0}개를 백업했습니다.`)}>원본 R2 백업</button></div>{exportMsg && <p className="reservoir-message" role="status">{exportMsg}</p>}</section>
    <section className="settings-section"><h2>고급 관리</h2><p>운영 중 데이터 품질을 보정할 때만 실행하세요. 작업 결과는 되돌리기 어렵습니다.</p><div className="settings-actions"><button className="ui-button-secondary" disabled={busy} onClick={() => void action("/api/search/embed-backfill?limit=25", setExportMsg, (data) => `자료 ${data.embedded ?? 0}개를 의미 색인했습니다. 남은 자료 ${data.remaining ?? 0}개.`)}>의미 색인 채우기</button><button className="ui-button-secondary" disabled={busy} onClick={() => void action("/api/reservoir/retag-all", setExportMsg, (data) => `자료 ${data.retagged ?? 0}개의 주제를 다시 분류했습니다.`)}>주제 다시 분류</button></div></section>
  </div>;
}
