import { useEffect, useState } from "react";
import PageHeader from "../components/layout/PageHeader";
import StatusMessage from "../components/ui/StatusMessage";

interface UsageSummary { month: string; budgetUsd: number; usedUsd: number; usedPct: number; calls: number; inputTokens: number; outputTokens: number; distillSessions: number; distillAvgCost: number; byPurpose: { purpose: string; calls: number; inputTokens: number; outputTokens: number; costUsd: number }[]; byModel: { model: string; calls: number; costUsd: number }[]; daily: { day: string; costUsd: number; calls: number }[]; months: { month: string; costUsd: number; calls: number }[]; }
const PURPOSE_LABEL: Record<string, string> = { analysis: "자료 분석", distill: "착즙", critic: "검토", counter: "반대 관점", embeddings: "색인" };

export default function UsageView() {
  const [data, setData] = useState<UsageSummary | null>(null);
  useEffect(() => { fetch("/api/usage/summary").then((response) => response.json() as Promise<UsageSummary>).then(setData).catch(() => setData(null)); }, []);
  if (!data) return <div className="view-stack"><PageHeader title="사용량" description="AI 작업의 비용과 월 한도를 확인합니다." /><StatusMessage kind="loading" title="사용량을 불러오는 중입니다" /></div>;
  const budgetState = data.usedPct >= 100 ? "BLOCKED" : data.usedPct >= 80 ? "WARNING" : "NORMAL";
  const stateText = budgetState === "BLOCKED" ? "월 한도에 도달했습니다. 착즙과 분석을 실행할 수 없습니다." : budgetState === "WARNING" ? "월 한도의 80% 이상을 사용했습니다. 남은 작업을 확인하세요." : "현재 월 한도 안에서 정상적으로 사용할 수 있습니다.";
  const maxDaily = Math.max(...data.daily.map((item) => item.costUsd), 0.001);
  return <div className="view-stack"><PageHeader title="사용량" description="AI 작업의 비용과 월 한도를 확인합니다." /><section className="usage-overview"><p className="reading-section__label">이번 달 · {data.month}</p><div className="usage-overview__amount">${data.usedUsd.toFixed(4)} <span>/ ${data.budgetUsd}</span></div><div className="usage-meter"><div className={`usage-meter__fill${budgetState === "WARNING" ? " is-warning" : budgetState === "BLOCKED" ? " is-blocked" : ""}`} style={{ width: `${Math.min(data.usedPct, 100)}%` }} /></div><p className={`usage-status${budgetState !== "NORMAL" ? ` is-${budgetState.toLowerCase()}` : ""}`}>{data.usedPct.toFixed(1)}% · {stateText}</p><p className="table-note">호출 {data.calls}회 · 입력 {(data.inputTokens / 1000).toFixed(1)}k · 출력 {(data.outputTokens / 1000).toFixed(1)}k · 착즙 {data.distillSessions}회 (평균 ${data.distillAvgCost.toFixed(4)})</p></section><section className="settings-section"><h2>작업별 사용량</h2><table className="data-table"><thead><tr><th>작업</th><th>호출</th><th>토큰 (입력/출력)</th><th>비용</th></tr></thead><tbody>{data.byPurpose.map((item) => <tr key={item.purpose}><td>{PURPOSE_LABEL[item.purpose] ?? item.purpose}</td><td>{item.calls}</td><td>{(item.inputTokens / 1000).toFixed(1)}k / {(item.outputTokens / 1000).toFixed(1)}k</td><td>${item.costUsd.toFixed(4)}</td></tr>)}</tbody></table></section><section className="settings-section"><h2>모델별 사용량</h2><div className="reading-keywords">{data.byModel.map((item) => <span key={item.model}>{item.model} · {item.calls}회 · ${item.costUsd.toFixed(4)}</span>)}</div></section>{data.daily.length > 0 && <section className="settings-section"><h2>일별 비용</h2><div className="daily-bars" aria-label="일별 비용 막대 그래프">{data.daily.map((item) => <div className="daily-bars__bar" key={item.day} title={`${item.day}: $${item.costUsd.toFixed(4)} · ${item.calls}회`} style={{ height: `${Math.max((item.costUsd / maxDaily) * 100, 3)}%` }} />)}</div><p className="table-note">막대에 마우스를 올리면 날짜별 비용과 호출 수를 확인할 수 있습니다.</p></section>}{data.months.length > 1 && <section className="settings-section"><h2>월별 기록</h2><p className="table-note">{data.months.map((item) => `${item.month} $${item.costUsd.toFixed(4)} · ${item.calls}회`).join("  ·  ")}</p></section>}<p className="table-note">Workers AI의 무료 할당량 사용은 이 비용 집계에 포함되지 않습니다.</p></div>;
}
